# Generated by Django 3.1.4 on 2021-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
