# Generated by Django 3.1.4 on 2021-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_gluteen_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_loctose_free',
            field=models.BooleanField(default=False),
        ),
    ]
