# Generated by Django 3.1.4 on 2021-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210522_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
