# Generated by Django 3.1.4 on 2021-07-01 11:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210611_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kakut', 'Kakut'), ('Fatayer', 'Fatayer'), ('Juustokakut', 'Juustokakut'), ('Manakish', 'Manakish'), ('Alkuruoat', 'Alkuruoat'), ('Kuppikakut', 'Kuppikakut')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6 People', '6 People'), ('8 People', '8 People'), ('12 People', '12 People'), ('16 People', '16 People'), ('20 People', '20 People')], max_length=47, null=True),
        ),
    ]
